import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../src/styles/Home.module.css";
import { HeaderSimple } from "../components/header";

const links = [
  {
    link: "",
    label: "About"
  },
  {
    link: "",
    label: "Blog"
  },
  {
    link: "",
    label: "Portfolio"
  },
  {
    link: "",
    label: "Contact"
  }
]

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderSimple links={links} />

      <div className="h-screen">
        hello
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
